# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 023874867911a8bed95d39a7a6ad4742c01cc0b7ada4d40394ff805643d6034484ecc06e45b2db49a2b56fd2e48c1d3094d9f8626dd63844b50c7e4b9ce0b3cd

test:
  secret_key_base: 87241f441fce1833c455c30e0f047b0ec653e169586901cfe671704763f3d61963039e67301635bd8a1a4abdc3b04f5a5b7461016d8e0ef5a6574b100000b08c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
